# Server Configuration
server:
  host: "0.0.0.0"
  port: 6000
  log_file: "./logs/logfile.txt"
  llm_log_file: "./logs/llm_logfile.txt"
  num_workers: 4
  num_audio_workers: 4
  usage:
    use_rate_limit: true
    rate_limit_xForwardedFor: false
    rate_limit_per_day: 1000000
    audio_cost_per_second: 100

# Ollama Configuration
chat_client:
  mode: "ollama"
  base_url: "http://host.docker.internal:11434"  # Connect to host machine's Ollama
  default_model: "mistral:latest"
  allowed_models: ["mistral:latest", "llama3.2:latest", "mistral", "llama3.2"]

# OpenAI Configuration
audio_client:
  mode: "kokoro"
  base_url: "http://host.docker.internal:8880/v1"  # Connect to host machine's Kokoro
  default_voice: "af_alloy"
  default_model: "kokoro"
  allowed_voices: ['af_alloy', 'af_aoede', 'af_bella', 'af_heart', 'af_jadzia', 'af_jessica', 'af_kore', 'af_nicole', 'af_nova', 'af_river', 'af_sarah', 'af_sky', 'af_v0', 'af_v0bella', 'af_v0irulan', 'af_v0nicole', 'af_v0sarah', 'af_v0sky', 'am_adam', 'am_echo', 'am_eric', 'am_fenrir', 'am_liam', 'am_michael', 'am_onyx', 'am_puck', 'am_santa', 'am_v0adam', 'am_v0gurney', 'am_v0michael', 'bf_alice', 'bf_emma', 'bf_lily', 'bf_v0emma', 'bf_v0isabella', 'bm_daniel', 'bm_fable', 'bm_george', 'bm_lewis', 'bm_v0george', 'bm_v0lewis', 'ef_dora', 'em_alex', 'em_santa', 'ff_siwis', 'hf_alpha', 'hf_beta', 'hm_omega', 'hm_psi', 'if_sara', 'im_nicola', 'jf_alpha', 'jf_gongitsune', 'jf_nezumi', 'jf_tebukuro', 'jm_kumo', 'pf_dora', 'pm_alex', 'pm_santa', 'zf_xiaobei', 'zf_xiaoni', 'zf_xiaoxiao', 'zf_xiaoyi', 'zm_yunjian', 'zm_yunxi', 'zm_yunxia', 'zm_yunyang']
  allowed_models: ["kokoro"]

liquidsoap_client:
  host: "liquidsoap"
  http_port: 8080

icecast_client:
  host: "icecast"
  port: 8000
  admin_password: "password"
  aitalkmaster_stream_endpoint_prefix: "http://localhost:6000/ait/stream/" # This variable will only be shown in the /ait/startConversation response to inform the user where to listen to for audio. Remove this variable when not using audio.
  translation_stream_endpoint_prefix: "http://localhost:6000/translation/stream/" # This variable will only be shown in the /translation/translate response to inform the user where to listen to for audio. Remove this variable when not using audio.


# Aitalkmaster Configuration
aitalkmaster:
  join_key_keep_alive_list: []